# Generated by Django 5.2.14 on 2026-05-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_publishedmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublishedManager",
        ),
    ]
