# Generated by Django 5.2.14 on 2026-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_delete_publishedmanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        ),
    ]
